version: "3.9"

services:
  app: 

    tty: true
    restart: always
    image: emergency-queue
    container_name: emergency-queue
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - application
    depends_on:
      - mongodb
    volumes:
      - .:/src/app
    command: air -c .air.toml  # Corrected indentation for `command`

  mongodb:
    restart: always
    image: mongo
    container_name: emergency-queue-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - application

volumes:
  mongodb:

networks:
  application:
